FROM grafana/loki:3.4.1

USER root
COPY loki/loki-config.yaml /etc/loki/config.yaml
USER loki

EXPOSE 3100

HEALTHCHECK --interval=10s --timeout=5s --start-period=30s --retries=3 \
  CMD wget -qO /dev/null http://localhost:3100/ready || exit 1

CMD ["-config.file=/etc/loki/config.yaml"]
